### ISSUE TITLE
Touch not working

### ISSUE THREAD

**Issue by leendevos** [chaeron/thermostat#1]
Hi Andrzej,

Great software, thanks! I do have an issue however the touch screen is not working and the mouse is not visible. It is on other kivy apps and works fine, so it shouldn't be a hardware issue. Any idea what it could be due to? I am running it on Raspberry Pi 2, with the official 7" touchscreen. Kivy version is 1.9.2. 

Kind regards,

Koen

**Comment by chaeron** [comment]
When using the touch screen with Kivy, there shouldn't be a mouse pointer visible.  Not sure what the problem is. Mine is running Kivy 1.9.1...maybe it's something in the new version.

**Comment by leendevos** [comment]
Maybe. I will look further and let you know if I found something.

**Comment by leendevos** [comment]
I found the issue : when running as sudo, the touch didn't work. Copying the config.ini to /root/.kivy solves the issue :-)
sudo cp ~/.kivy/config.ini /root/.kivy/config.ini
